Fix "nodepool image-update provider label" cmd
Steps to reproduce:

nodepool@ci-repomaster:~$ nodepool image-update local_01 test
Traceback (most recent call last):
  File "/usr/local/bin/nodepool", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nodepool/cmd/nodepoolcmd.py", line 307, in main
    return npc.main()
  File "/usr/local/lib/python2.7/dist-packages/nodepool/cmd/nodepoolcmd.py", line 300, in main
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/nodepool/cmd/nodepoolcmd.py", line 189, in image_update
    self.pool.updateImage(session, provider.self.args.image)
AttributeError: 'Provider' object has no attribute 'self'

Change-Id: Ib28fb88e6970bb5819b1fc4e537ad0550eb65a51
Fix: Update the usage of updateImage in 'else' clause to match the usage in the 'if' clause.