Fix dict key copy operation
The dict keys() method returns an iterator in py3, so we are not
actually getting a copy of the keys on simple assignment. So when
the dict is modified, we can still get:

   RuntimeError: dictionary changed size during iteration

Explicitly create a new list using the keys to prevent this.

Change-Id: If4a8b8c65d66a162dc384104e4613e7f2f70a8b0